[project]
name = "dao-treasury"
description = "Time-locked DAO Treasury with Streaming Payments"
authors = ["developer"]
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.dao-treasury]
path = "contracts/dao-treasury.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
